const product = [
    {
        id: 1,
        title: 'realme 3 Pro (Prosesor Snapdragon 710 AIE VOOC Flash Charge 3.0)',
        category: 'Handphone',
        subcategory: '',
        price: 3699000,
        city: 'Banten',
        star: '1234',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/f8971c6eb0d86e69ee79df76c76f7253.jpg', 'https://id-test-11.slatic.net/p/f8971c6eb0d86e69ee79df76c76f7253.jpg', '']
    },
    {
        id: 2,
        title: 'realme 3 [MediaTek Helio P60 4230mAh battery]',
        category: 'Handphone',
        subcategory: '',
        price: 1999000,
        city: 'Banten',
        star: '7345',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/5da9825f9b6d59f8713763eb5b7bc3f1.jpg', 'https://id-test-11.slatic.net/p/5da9825f9b6d59f8713763eb5b7bc3f1.jpg', '']
    },
    {
        id: 3,
        title: 'Samsung Galaxy A20',
        category: 'Handphone',
        subcategory: '',
        price: 2009000,
        city: 'Jawa Barat',
        star: '2282',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/bb75b5aa1b95ea16c10b6adc4b35ace2.jpg', 'https://id-test-11.slatic.net/p/1186c6cbd94a8c0b555e678f13f52924.jpg', '']
    },
    {
        id: 4,
        title: 'Samsung Galaxy Note9 6/128GB',
        category: 'Handphone',
        subcategory: '',
        price: 11699000,
        city: 'Jawa Barat',
        star: '543',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/8a27295f329ae64c77a025a1aae5276e.jpg', 'https://id-test-11.slatic.net/p/8a27295f329ae64c77a025a1aae5276e.jpg', '']
    },
    {
        id: 5,
        title: 'Xiaomi Redmi Note-7 48MP Ram 4 ROM 64/128GB Garansi Distributor',
        category: 'Handphone',
        subcategory: '',
        price: 2405000,
        city: 'DKI Jakarta',
        star: '242',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/df62ba76fffa84de6e98019d4c0a74cd.jpg', 'https://id-test-11.slatic.net/p/9546ead0af3e2f5ccba068998389e9a2.jpg', '']
    },
    {
        id: 6,
        title: 'Samsung Galaxy Note8 - Midnight Black',
        category: 'Handphone',
        subcategory: '',
        price: 8499000,
        city: 'Jawa Barat',
        star: '867',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/8eec65319407473ad70d71bc6a87e717.jpg', 'https://id-test-11.slatic.net/p/8eec65319407473ad70d71bc6a87e717.jpg', '']
    },
    {
        id: 7,
        title: 'Samsung Galaxy A50 - 4GB/64GB',
        category: 'Handphone',
        subcategory: '',
        price: 3395000,
        city: 'Jawa Barat',
        star: '822',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/2058c299eb37c07f61940808494ddb93.jpg', 'https://id-test-11.slatic.net/p/4d26e8dd71eccebb00204c5e2f869239.jpg', '']
    },
    {
        id: 8,
        title: '',
        category: 'Handphone2',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    },
    {
        id: 9,
        title: '',
        category: 'Handphone2',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    },
    {
        id: 10,
        title: '',
        category: 'Handphone',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    }, {
        id: 11,
        title: '',
        category: '',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    }, {
        id: 12,
        title: '',
        category: '',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    }, {
        id: 13,
        title: '',
        category: '',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    }, {
        id: 14,
        title: '',
        category: '',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    },
    {
        id: 15,
        title: '',
        category: '',
        subcategory: '',
        price: 1,
        city: '',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['', '', '']
    },
]

export default product
