const product = [
    {
        id: 1,
        title: 'realme 3 Pro (Prosesor Snapdragon 710 AIE VOOC Flash Charge 3.0)',
        category: 'Handphone',
        subcategory: '',
        price: 3699000,
        city: 'Banten',
        star: '4',
        ulasan: '1234',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/f8971c6eb0d86e69ee79df76c76f7253.jpg', 'https://id-test-11.slatic.net/p/3c27a62718f080e4b88d8ca1d5fb5dea.jpg', 'https://id-test-11.slatic.net/p/a0be79358a6fb8c7c97cc9d4e3bcb040.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 2,
        title: 'realme 3 [MediaTek Helio P60 4230mAh battery]',
        category: 'Handphone',
        subcategory: '',
        price: 1999000,
        city: 'Banten',

        star: '4',
        ulasan: '7345',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/5da9825f9b6d59f8713763eb5b7bc3f1.jpg', 'https://id-test-11.slatic.net/p/2250fade00c63250a6c48ce79d35bede.jpg', 'https://id-test-11.slatic.net/p/e6582754f192860c6fe3b39ba8169942.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 3,
        title: 'Samsung Galaxy A20',
        category: 'Handphone',
        subcategory: '',
        price: 2009000,
        city: 'Jawa Barat',

        star: '5',
        ulasan: '2282',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/bb75b5aa1b95ea16c10b6adc4b35ace2.jpg', 'https://id-test-11.slatic.net/p/1186c6cbd94a8c0b555e678f13f52924.jpg', 'https://id-test-11.slatic.net/p/6380393ce7a637ce807234f4a1d3d687.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 4,
        title: 'Samsung Galaxy Note9 6/128GB',
        category: 'Handphone',
        subcategory: '',
        price: 11699000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '543',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/8a27295f329ae64c77a025a1aae5276e.jpg', 'https://id-live-01.slatic.net/original/883d20094343fee5bd35c752e768f4ab.jpg', 'https://id-test-11.slatic.net/p/4d7b1cdfadebbd66340b44829261c6ed.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 5,
        title: 'Xiaomi Redmi Note-7 48MP Ram 4 ROM 64/128GB Garansi Distributor',
        category: 'Handphone',
        subcategory: '',
        price: 2405000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '242',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/df62ba76fffa84de6e98019d4c0a74cd.jpg', 'https://id-test-11.slatic.net/p/9546ead0af3e2f5ccba068998389e9a2.jpg', 'https://id-test-11.slatic.net/p/91f9305378a9caf846728bc50d03fc09.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 6,
        title: 'Samsung Galaxy Note8 - Midnight Black',
        category: 'Handphone',
        subcategory: '',
        price: 8499000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '867',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/8eec65319407473ad70d71bc6a87e717.jpg', 'https://id-test-11.slatic.net/p/9a7645f6689ef47d7765a7a547793c29.jpg', 'https://id-live-01.slatic.net/original/1c1fddc6c39fee0aa7d45d7ed905ee6b.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 7,
        title: 'Samsung Galaxy A50 - 4GB/64GB',
        category: 'Handphone',
        subcategory: '',
        price: 3395000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '822',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/2058c299eb37c07f61940808494ddb93.jpg', 'https://id-test-11.slatic.net/p/4d26e8dd71eccebb00204c5e2f869239.jpg', 'https://id-test-11.slatic.net/p/2d5e935abfaa951845bf4d8165238290.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 8,
        title: 'Samsung Galaxy S10+ 128GB',
        category: 'Handphone',
        subcategory: '',
        price: 11899000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '113',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/e9731078ce854193bcf3530586430e54.jpg', 'https://id-test-11.slatic.net/p/639e158eb2cce9c6e64b267d7be46e05.jpg', 'https://id-test-11.slatic.net/p/091dd7d45c3793590b152a1c2e0021b1.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 9,
        title: 'Samsung Galaxy A70',
        category: 'Handphone',
        subcategory: '',
        price: 5289000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '256',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/2d59e557016e2626d6fe91181395bc2e.jpg', 'https://id-test-11.slatic.net/p/3a7f5531c6016a307765beaad7900977.jpg', 'https://id-test-11.slatic.net/p/a55d1ab87a8be07db2a7a44944137ebf.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 10,
        title: 'Samsung Galaxy A7 2018 4/64 GB',
        category: 'Handphone',
        subcategory: '',
        price: 3489000,
        city: 'Banten',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/572bf374ecbb0ab010a33405df05fe48.jpg', 'https://id-test-11.slatic.net/p/5cdd75aa1c2e7c83fd34e6cdd52a4ad9.jpg', 'https://id-test-11.slatic.net/p/ae77ffa519fc62364047c971162cce61.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    }, {
        id: 11,
        title: 'Huawei Y7 Pro 2019',
        category: 'Handphone',
        subcategory: '',
        price: 1899000,
        city: 'Jawa Barat',
        star: '4',
        ulasan: '1066',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/9404ab9dc386d25a36157c83bb005ea6.jpg', 'https://id-test-11.slatic.net/p/e25a6ebb923f14b426556294782f2c88.jpg', 'https://id-test-11.slatic.net/p/e6d45eb2e11a936136fc92e6f5c2d66c.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    }, {
        id: 12,
        title: 'Realme 3 Pro Smartphone [6GB / 128GB] Garansi Resmi Promo',
        category: 'Handphone',
        subcategory: '',
        price: 3599000,
        city: 'Jawa Barat',
        star: '4',
        ulasan: '17',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/f7dd6706fd042ce117bc22be709e15ea.jpg', 'https://id-test-11.slatic.net/p/60a0660981ef146f328371cf2c633da5.jpg', 'https://id-test-11.slatic.net/p/793a0dc5719b068f7588d638d9302771.jpg'],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    }, {
        id: 13,
        title: 'Apple iPhone 8 Plus 256GB Perak',
        category: 'Handphone',
        subcategory: '',
        price: 16199000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/2/apple-iphone-8-plus-perak-256gb-1513246820-62887376-691f20bfb59be8bb935ccf9989d03f3e-catalog.jpg_200x200q80.jpg_.webp', 'https://id-test-11.slatic.net/p/2/apple-iphone-8-plus-abu-abu-64gb-1513246837-53887376-0e56e8672c2a4c705eccdadf788ce21f-catalog.jpg_200x200q80.jpg_.webp', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    }, {
        id: 14,
        title: 'NOKIA X6 hp Nokia 6.1 Plus 6G/64G - COD, Gratis Ongkir, AI Facial Unlock, Snapdragon 636, Fingerprint Unlock',
        category: 'Handphone',
        subcategory: '',
        price: 2595000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '249',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/9975efe76cfab461406a1df2e4760a28.jpg', 'https://id-test-11.slatic.net/p/7d81b4de732b5caa4910e9ebfdf90f1a.jpg', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 15,
        title: 'OPPO RENO 6GB / 256GB',
        category: 'Handphone',
        subcategory: '',
        price: 699000,
        city: 'DI Yogyakarta',
        star: '',
        ulasan: '',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/9c20fa6043e50a7e2a7f5d18f6af5fd1.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 16,
        title: 'Huawei P30 lite hp 6G/128G - COD, Gratis Ongkir, 32 MP AI Selfie Superstar, Ultra Wide Triple Camera, Garansi resmi',
        category: 'Handphone',
        subcategory: '',
        price: 3899000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '59',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/76ce532e6e23428ace5d5e0b06aa48a8.jpg', 'https://id-test-11.slatic.net/p/77dd93fe132388a84d56498d703daa06.jpg', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 17,
        title: 'Vivo Y95 4GB RAM 64GB ROM',
        category: 'Handphone',
        subcategory: '',
        price: 2399000,
        city: 'Banten',
        star: '5',
        ulasan: '15',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/d825ecf9e7aadb37c8b47a0a0eaf7505.jpg', 'https://id-test-11.slatic.net/p/45d4ace2b6a2354b31c6caf8b44f360c.jpg', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 18,
        title: 'Nokia 5.1 Plus - 5.86 " - RAM 3GB / ROM 32 GB - Batt 3060 mAh - Garansi Resmi',
        category: 'Handphone',
        subcategory: '',
        price: 1950000,
        city: 'North Sumatra',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/a8300ad6315a0145b5d0e018cd5407c4.jpg', 'https://id-test-11.slatic.net/p/fd93bf56680fcb44346737904f45d4bd.jpg', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 19,
        title: 'Huawei P30 Pro hp 8G/256G - COD, Gratis Ongkir, with 50x zoom, is protected with IP68 water and dust,Garansi resmi ',
        category: 'Handphone',
        subcategory: '',
        price: 11590000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '32',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/7f7c87703a0b12b9a990e44728f26f2a.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 20,
        title: 'Xiaomi Mi Play 4/64GB ROM - Miplay Global Version - Bukan Redmi 7',
        category: 'Handphone',
        subcategory: '',
        price: 1850000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '9',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/4321ea3423e20d32fef9743410a8e699.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 21,
        title: 'Notebook Asus X441MA-GA012T - Intel® Celeron® N4000- 4GB - 1Tb - intel graphic HD - 14" - W10 - Silver',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 4054000,
        city: 'Jawa Barat',
        star: '4',
        ulasan: '96',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/6ae06dfe526b203bc4fb292f8cb3ae50.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 22,
        title: 'Notebook Baru Asus A407MA-BV001T - Intel® Celeron® N4000 - RAM 4GB - 1TB - Intel UHD Graphics 600 - 14.0 - W10 - Grey',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 3909000,
        city: 'Jawa Barat',
        star: '4',
        ulasan: '210',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/ddec71a6c64fc3d46b4f22cfc5466008.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 23,
        title: 'Baik 10.1 Inch Komputer Tablet RAM 4G ROM 64G Dual Kartu Dual Kamera',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 999000,
        city: 'Tiongkok',
        star: '3',
        ulasan: '66',
        pertanyaan: '',
        url: ['https://my-live-02.slatic.net/original/5944f2a83db5623ed8138a67be75f529.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 24,
        title: 'Asus VivoBook E203MA-TBCL232A | Intel N4000 | 2GB RAM DDR4 | 32Gb EMMC | 11.6 HD LED | Windows 10 | Grey',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 2909000,
        city: 'Jawa Timur',
        star: '4',
        ulasan: '12',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/af5c654e20f2b0c8249b5760c0a49000.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 25,
        title: 'Notebook Baru Asus X441MA-GA012T - Intel® Celeron® N4000- 4GB - 1Tb - intel graphic HD - 14" - W10 - Silver',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 4054000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '96',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/6ae06dfe526b203bc4fb292f8cb3ae50.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 26,
        title: 'Notebook Baru Lenovo Ideapad 130-14AST - AMD A4-9125 - 4GB - 500GB - AMD Radeon R3 - 14" - W10 - Black',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 3749000,
        city: 'Jawa Barat',
        star: '4',
        ulasan: '12',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/8892cbcd361de87bd5a446313c02c6c5.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 27,
        title: 'Acer Aspire 3 A315-41-R97J - AMD Ryzen R5 2500U - RAM 8GB - 1TB - Radeon RX Vega 8 - 15.6" - Windows 10 - Obsidian Black',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 7219000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/17be8633c19b1ebc9c7a3af3c44a9efe.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 28,
        title: 'Notebook Baru Apple macbook Air - intel core i5 - RAM 8GB - 256 GB - Intel HD Graphics 6000 - 13" - Mac os - Gold',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 21690000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '100',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/d122c8ffdbcb6d0ce1251be6e5e28e19.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 29,
        title: 'Apple macbook Air - intel core i5- RAM 8GB - 256 GB - Intel HD Graphics 6000 - 13"- Mac os Space Grey',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 21256200,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/da574e0ba55ceee4464ebae61a12abc1.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 30,
        title: 'Apple Macbook Pro MPXR2 - Intel Core i5 - RAM 8GB - 128GB SSD - 13.3" - Mac OS - Silver',
        category: 'Laptop',
        subcategory: 'LaptopConsumer',
        price: 19159000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '20',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/2/apple-macbook-pro-mpxr2-intel-core-i5-ram-8gb-128gb-ssd-13339-mac-os-silver-1512399491-90094555-2160a0e1367bd37007419434a801ddd5-catalog_233.jpg', '', '']
    },
    {
        id: 31,
        title: 'Asus ROG GL503GE-EN023T-Intel® Core™ i7-8750H - RAM 8G-1TB SSHD - NVIDIA GeForce GTX 1050 Ti - 15.6" - W10 - Metal Black',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 15399000,
        city: 'Jawa Barat',
        star: '5',
        ulasan: '54',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/f906c7cb8179a56b6cd931e9701fe5d5.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 32,
        title: 'Dell G7-7588 [15.6", Ci7-8750H, 8GB, 1TB+128GB, Nvidia 4GB, Windows 10 SL, Hitam]',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 19199000,
        city: 'DKI Jakarta',
        star: '4',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/9209a0e4b334e4bb3cca4d24bd5c8274.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 33,
        title: 'ASUS TUF Gaming FX505GE-I7T61T - Core i7-8750H - 8GB - (128GB SSD + 1TB HDD) - NVidia GTX1050Ti-4GB - 15.6" FHD - Win10 Home - Gold Steel - ESEL',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 15798000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/7bf192088d01b2dbd3f40cf0a8c5776a.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 34,
        title: 'ASUS ROG GL503GE HERO - i7 8750H - 16GB - 128GB SSD + 1TB - GTX1050TI - W10 - 15.6" FHD',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 17990000,
        city: 'Banten',
        star: '5',
        ulasan: '4',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/945df7362d0f498d95b2031108d75a45.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 35,
        title: 'Asus Tuf Gaming Fx505Dd - R5581T [ AMD R5 - 3350H/ 8GB/ 1TB Hdd/ Gtx1050 3GB/ Win10 ] Gun Metal',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 9999000,
        city: 'North Sumatra',
        star: '4',
        ulasan: '5',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/123524c2e14d212b29be111a3dd50a9a.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 36,
        title: 'Acer Nitro 5 AN515-54-512L [ Core i5-9300H/ 8GB DDR4/ 256GB M.2/ GTX1650 4GB/ Win10 ] Black',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 15699000,
        city: 'North Sumatra',
        star: '5',
        ulasan: '7',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/eade09842462753fd1bfb0a9fa6115f5.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 37,
        title: 'Asus ROG Zephyrus G GA502DU-R76601T [ 8GB/ 512GB NVMe/ GTX1660Ti 6GB/ Win10 ] Black',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 19999000,
        city: 'North Sumatra',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/540d915e57d7c2ddea03033260bcd651.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 38,
        title: 'Asus ROG GL503GE-EN023T - Intel® Core™ i7-8750H - RAM 8GB -1TB SSHD - NVIDIA GeForce GTX 1050 Ti - 15.6" ',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 16229000,
        city: 'Banten',
        star: '5',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/d6b978902456403bd92ed004621ffaff.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 39,
        title: 'Asus Tuf Gaming Fx505Ge - I5T61T [ Core i5 - 8300/ 8GB/ 1TB Hdd/ GTX1050Ti 4GB/ Win10 ] Gun Metal',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 12999000,
        city: 'North Sumatra',
        star: '5',
        ulasan: '4',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/05ab37949a76d167a35af3135069e831.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 40,
        title: 'MSI GL63 8SE-088 [Core I5/ 8GB Ddr4/ 128GB Ssd/ 1TB HDD/ RTX2060 6GB/ Win10] Black',
        category: 'Laptop',
        subcategory: 'LaptopGaming',
        price: 19999000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '8',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/90565298e3bfcefa3b9c4f3933824598.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 41,
        title: 'Lenovo Ideapad Yoga 520-14IKB-PQID GRAY Ci3-7020U - 8GB - 1TB - MX130 2GB - Windows 10 Home - 2yr',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 8999000,
        city: 'Indonesia',
        star: '3',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://id-live-01.slatic.net/original/757490d538b3b2af52af8ac43a790f76.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 42,
        title: 'Lenovo Yoga C340-14IWL-8MID Onyx Black with Stylus (Core i7-8565U - 16GB DDR4 - 1TB SSD M.2 - NVIDIA MX230 2GB',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 15299000,
        city: 'Indonesia',
        star: '5',
        ulasan: '10',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/15d3fb4a07a2118df40fdcb5dbf365e7.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 43,
        title: 'LENOVO IDEAPAD D330 - N4000 - RAM 4GB - 128GB eMMC, 10.1 INCH - WIN 10 - GRAY (81H3007EID)',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 4299000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '4',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/7310dd669b65fa3da45ca0cf76669c5d.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 44,
        title: 'Dell Inspiron 5482 [14.0", Ci3-8145U, 4GB, 1TB, Intel HD, Windows 10 SL, Grey]',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 9199000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/1040a94f178c401b5c28fb1a5eade4b0.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 45,
        title: 'CHUWI Herobook 14.1 Inch Laptop Windows 10 Intel E8000 Quad Core 4 GB RAM 64 GB ROM Notebook dengan Tata Letak Penuh KEyboard',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 3741000,
        city: 'Tiongkok',
        star: '4',
        ulasan: '1',
        pertanyaan: '',
        url: ['https://my-test-11.slatic.net/p/84ed03e3d7aee3ec07b7ea429a7483cf.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 46,
        title: 'HP ENVY X360 13-AG0022AU - RYZEN 5 2500U-8GB-512GB-WIN10-13.3FHD TOUCH',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 1,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '14495000',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/c670b9d7c96bd78446ce2b8da1805e93.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 47,
        title: 'E-ERA 15.6 Inci Ultra Slim Laptop HD Diaktifkan Kamera Wifi Notebook Bluetooth',
        category: '',
        subcategory: 'Laptop2-in-1s',
        price: 4538000,
        city: 'Tiongkok',
        star: '4',
        ulasan: '2',
        pertanyaan: '',
        url: ['https://my-live-02.slatic.net/original/0ed58e9f3153af0452a1f677d88efe7e.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 48,
        title: '15.6 Inch 2 + 32 GB Laptop HD Diaktifkan Kamera Wifi Laptop Notebook',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 4000000,
        city: 'Tiongkok',
        star: '4',
        ulasan: '3',
        pertanyaan: '',
        url: ['https://my-test-11.slatic.net/p/914eaf1f9ee289d5a4300f00d96f80b5.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 49,
        title: 'Notebook PC Tahan Lama Silver 1536X864',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 8000000,
        city: 'Tiongkok',
        star: '5',
        ulasan: '4',
        pertanyaan: '',
        url: ['https://my-test-11.slatic.net/p/3aa62185623f3c54f2decec41c306909.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },
    {
        id: 50,
        title: 'DELL Inspiron 7386 Laptop - Silver [13.3" FHD Touch/ Core i7-8565U/ Memory 16GB/SSD 512GB/ Intel HD/ Windows 10',
        category: 'Laptop',
        subcategory: 'Laptop2-in-1s',
        price: 22000000,
        city: 'DKI Jakarta',
        star: '5',
        ulasan: '6',
        pertanyaan: '',
        url: ['https://id-test-11.slatic.net/p/ac508011e982414f9321eb96227cd35d.jpg', '', ''],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." 
    },

]

export default product

